### ISSUE TITLE
No setting selected when loading a measure

### ISSUE THREAD

**Issue by lcontami** [Ecpy/ecpy_hqc_legacy#36] opened 2017-12-11 10:56 UTC
When loading a measure involving an instrument with a setting, the previous selected setting is not selected from the dropdown list.
It is however present in the measure .ini file

**Comment by MatthieuDartiailh** [comment] 2017-12-11 12:26
Closing as we cannot reproduce actually.

**Closed as completed by MatthieuDartiailh** 2017-12-11 12:26 UTC
